defaultChannel: Global
defaultTag: ""

globalChannels:
  - name: Global
    aliases: [global, server]
    shortcut:
    color: GRAY
    format: "[<channel.name>] <sender.color>[<sender.tag>] <channel.color><sender.name>: <text>"
    permission:

localChannels:
  - name: Local
    aliases: [local, say, s]
    shortcut: "(("
    color: WHITE
    format: "<sender.color>[<sender.tag>] <channel.color><sender.name>: <text>"
    radius: 30
