defaultChannel: Global

globalChannels:
  - name: Global
    aliases: []
    shortcut:
    color: GRAY
    formatString: "[<channel.name>] <sender.color>[<sender.tag>] <channel.color><sender.name>: <text>"
    permission:

localChannels:
  - name: Local
    aliases: [say, s, rp]
    shortcut: "(("
    color: WHITE
    formatString: "<sender.color>[<sender.tag>] <channel.color><sender.name>: <text>"
    radius: 30
