name: "WarCraft_Chat"
version: 15.0.0-SNAPSHOT
api-version: "1.15"

author: fishb6nes
authors: [fishb6nes, cbngu]
website: http://warcraft.gg

main: gg.warcraft.chat.spigot.ChatPlugin
depend: ["WarCraft_Monolith"]
